version: '3.9'

services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    networks:
      - network
    environment:
      - POSTGRES_URL=postgresql://postgres:postgres@db/visualisation_db
    depends_on:
      - db

  db:
    image: postgres:bullseye
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: visualisation_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: db
    networks:
      - network


volumes:
  postgres_data:

networks:
  network:
    driver: bridge