name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get install -y docker-compose
          sudo chmod +x /usr/local/bin/docker-compose


      - name: Build and Deploy
        run: |
          docker-compose up -d